// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwHRVyfFKZFObFe5neTG-cyuSD24SNSvY',
    appId: '1:571016803264:web:60e213285052d4af7f4e25',
    messagingSenderId: '571016803264',
    projectId: 'apps-for-good---umass-nav',
    authDomain: 'apps-for-good---umass-nav.firebaseapp.com',
    storageBucket: 'apps-for-good---umass-nav.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4owxvxon5sq094dQtNbRJX16s_EoXOPw',
    appId: '1:571016803264:android:62befc9431dcda6d7f4e25',
    messagingSenderId: '571016803264',
    projectId: 'apps-for-good---umass-nav',
    storageBucket: 'apps-for-good---umass-nav.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw_QWhVKlGA8cNRcU8UxCGbFNUkC3wEW8',
    appId: '1:571016803264:ios:1aa6e18cf046923d7f4e25',
    messagingSenderId: '571016803264',
    projectId: 'apps-for-good---umass-nav',
    storageBucket: 'apps-for-good---umass-nav.appspot.com',
    iosClientId: '571016803264-dehlgdi36jjk4rp51755djp28gje87dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWorkspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw_QWhVKlGA8cNRcU8UxCGbFNUkC3wEW8',
    appId: '1:571016803264:ios:1aa6e18cf046923d7f4e25',
    messagingSenderId: '571016803264',
    projectId: 'apps-for-good---umass-nav',
    storageBucket: 'apps-for-good---umass-nav.appspot.com',
    iosClientId: '571016803264-dehlgdi36jjk4rp51755djp28gje87dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWorkspace',
  );
}
